To check and integrate my UT and IT
preetham-b-capillary/node-TDD pull request #3
Opened 2022-06-30 07:04 UTC by milind30082000

2022-06-30 13:29 UTC, preetham-b-capillary requested changes

2022-06-30 13:29 UTC, preetham-b-capillary commented on src/mapper/calculator.js
> +      break;
handle division error, add a try catch

2022-07-01 10:33 UTC, milind30082000 commented on src/mapper/calculator.js
> +      break;
I have handled the division by zero error as in JS when we divide by zero it return Infinity.

2022-07-01 12:26 UTC, hitesh-cap approved these changes

2022-08-09 04:28 UTC, closed without merging